### ISSUE TITLE
Document deployment setup at https://guts-explorer.s5n.nl/

### ISSUE THREAD

**Issue by jsheunis** [guts-consortium/guts-explorer-backend#3]
Some updates were done on that server compared to the setup in the guts backend and frontend github repos. These changes need to be documented so that they can be reused or learnt from for the kubernetes deployment.

**Comment by jsheunis** [comment]
### Structure

This is the directory structure of the `guts-explorer` repository ([source](https://github.com/guts-consortium/guts-explorer)) in the home dir of a user on the server:

```
guts-explorer
.
├── backend
│   ├── certs
│   ├── data
│   ├── Dockerfile.cron
│   ├── Dockerfile.flask
│   ├── LICENSE
│   ├── README.md
│   ├── requirements.txt
│   ├── src
│   └── update_metadata_entrypoint.sh
├── docker-compose.yml
├── docs
├── frontend
│   ├── dist
│   ├── Dockerfile
│   ├── index.html
│   ├── jsconfig.json
│   ├── nginx.conf
│   ├── node_modules
│   ├── package.json
│   ├── package-lock.json
│   ├── public
│   ├── README.md
│   ├── src
│   └── vite.config.mjs
├── LICENSE
├── package.json
├── package-lock.json
└── README.md
```

The `docker-compose.yml` file in the root has content:

```yaml
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.flask
    ports:
      - "5010:5000"
    environment:
      # Load environment variables from a file
      # Developers need to create a .env file in the frontend root
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
      - data:/app/data
    command: ["python", "-m", "flask", "--app", "src/app", "run", "--host=0.0.0.0", "--port=5000"]


  metadata_updater:
    build:
      context: ./backend
      dockerfile: Dockerfile.cron
    volumes:
      - ./backend:/app
      - data:/app/data

volumes:
  data:
    driver: local
```

### Dockerfiles and associated helper files
 
#### The flask app (i.e. backend api): `backend/Dockerfile.flask`

```
# Use Python as the base image
FROM python:3.11

# Set working directory
WORKDIR /app

# Set the PYTHONPATH to /app/backend/src
ENV PYTHONPATH=/app/backend/src:$PYTHONPATH

# Copy requirements.txt and install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app
COPY . .

CMD ["python", "-m", "flask", "--app", "src/app", "run"]
```

#### The cron job to update metadata: `backend/Dockerfile.cron`

```
# Use Python as the base image
FROM python:3.11

# Set working directory
WORKDIR /app

# Install cron
RUN apt-get update && apt-get install -y cron

# Copy requirements.txt and install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app
COPY . .

# Copy entrypoint script
COPY update_metadata_entrypoint.sh /app/update_metadata_entrypoint.sh
RUN chmod +x /app/update_metadata_entrypoint.sh

# Start cron job for metadata updater
ENTRYPOINT ["/app/update_metadata_entrypoint.sh"]
```

The associated `update_metadata_entrypoint.sh` script:
```
#!/bin/bash

# Write cron job to run update_metadata.py daily at 02:00 UTC
echo "0 2 * * * python /app/src/update_metadata.py" > /etc/crontabs/root

# Start the cron service
crond -f -l 2%
```


#### The frontend: `frontend/Dockerfile`

```
# Use Node.js as the base image
FROM node:20 AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Ensure node_modules/.bin is in PATH
ENV PATH="/app/node_modules/.bin:$PATH"

# Copy the rest of the app's code
COPY . .

# Build
RUN npm run build

# Serve step
FROM nginx:alpine

# Remove default nginx config and add our own
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy built frontend files
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
```

The associated `nginx.config`:

```
server {
    listen 80;

    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }
}
```

#### Command to deploy via docker:

From the root directory:
```
sudo docker compose up -d  --build
```

### Deployment

Initial troubles were experienced with both the frontend and backend docker deployments.

This led to the temporary decisions (on this particular infra) to:
- serve the frontend static files (after build) via Caddy, and to 
- deploy the backend metadata updater cron job via docker
- deploy the backend flask api app via docker, with a Caddy reverse proxy to serve it via the correct domain


#### Caddyfile

The content of the Caddyfile at `/etc/caddy/Caddyfile`:

```
# GUTS explorer
guts-explorer.s5n.nl {
    root * /var/www/html/guts-explorer
    file_server

    reverse_proxy /api/* localhost:5010
}

# Redirect all HTTP to HTTPS
http:// {
    redir https://{host}{uri}
}
```

#### Frontend static files

These are built with vite from the frontend repo, and copied to `/var/www/html/guts-explorer`

```
/var/www/html/guts-explorer
├── assets
│   ├── fa-brands-400-DGgeaIc2.woff2
│   ├── fa-regular-400-BZeDGO4g.woff2
│   ├── fa-solid-900-BVqQ4OpK.woff2
│   ├── Helvetica-Neue-LT-W01-55-Roman-EAIs8dHO.woff2
│   ├── Helvetica-Neue-LT-W05-75-Bold-Ci5dzcvz.woff2
│   ├── Helvetica-Neue-LT-W05-85-Heavy-C6dLb5Fn.woff2
│   ├── homepage-DB2CIwyL.png
│   ├── index-Byxdd8qN.css
│   ├── index-CKBilm16.js
│   ├── logo_Amsterdam_UMC-vF3pwpms.webp
│   ├── logo_eur-BFe-aMsF.png
│   ├── logo_funding-B_iHGma6.webp
│   ├── logo_groningen-D0tMjqg9.webp
│   ├── logo_guts-DqYDlz36.svg
│   ├── logo_NIFN-DPlxnmZU.webp
│   ├── logo_RADBOUDMC-C31mH8W0.webp
│   ├── logo_unileiden-BBzHY45N.webp
│   ├── logo_utrechtuni-SDR-l5SG.webp
│   ├── logo_uva-B9aE1RTo.webp
│   ├── logo_vrije-423bMmnS.png
│   ├── materialdesignicons-webfont-CgCzGbLl.woff
│   ├── materialdesignicons-webfont-CYDMK1kx.woff2
│   ├── materialdesignicons-webfont-D3kAzl71.ttf
│   └── materialdesignicons-webfont-DttUABo4.eot
├── CNAME
├── favicon.ico
└── index.html
```

(The CNAME file is unused here)
